print("Hello World!")
print("\nThis is the 2nd sentence.")
print("\nThis is the 3rd sentence.")
print("\nThis is the 4th sentence.")
print("\nThis is the 5th sentence.")
print("\nThis is the 6th sentence.")
