print("=========================")   
print("    SIMPLE CALCULATOR")  
print("=========================")   
print("[1] Addition")
print("[2] Subtraction")
print("[3] Multiplication")
print("[4] Division")
print("[5] Exponentation")
print("[6] Modulo")
print("[7] Floor Division")
print("[8] Exit")
print("=========================")

choice = int(input("\nEnter your choice: "))
